//getAllEmployee
export const GET_ALL_EMPLOYEES_OK = 'GET_ALL_EMPLOYEES_OK';
export const GET_ALL_EMPLOYEES_ERROR = 'GET_ALL_EMPLOYEES_ERROR';
//getEmployee
export const GET_EMPLOYEE_OK = 'GET_EMPLOYEE_OK';
export const GET_EMPLOYEE_ERROR = 'GET_EMPLOYEE_ERROR';
export const GETTING_EMPLOYEE = 'GETTING_EMPLOYEE';
//addEmployee
export const HANDLE_INPUT_NAME_ADD = 'HANDLE_INPUT_NAME_ADD';
export const HANDLE_INPUT_ROLE_ADD = 'HANDLE_INPUT_ROLE_ADD';
export const HANDLE_INPUT_EMAIL_ADD = 'HANDLE_INPUT_EMAIL_ADD';

export const ADDING_EMPLOYEE = 'ADDING_EMPLOYEE';
export const ADD_EMPLOYEE_OK = 'ADD_EMPLOYEE_OK';
export const ADD_EMPLOYEE_ERROR = 'ADD_EMPLOYEE_ERROR';
//updateEmployee
export const HANDLE_INPUT_NAME_UPDATE = 'HANDLE_INPUT_NAME_UPDATE';
export const HANDLE_INPUT_ROLE_UPDATE = 'HANDLE_INPUT_ROLE_UPDATE';
export const HANDLE_INPUT_EMAIL_UPDATE = 'HANDLE_INPUT_EMAIL_UPDATE';

export const UPDATING_EMPLOYEE = 'UPDATING_EMPLOYEE';
export const UPDATE_EMPLOYEE_OK = 'UPDATE_EMPLOYEE_OK';
export const UPDATE_EMPLOYEE_ERROR = 'UPDATE_EMPLOYEE_ERROR';
