export default styles = {
		container:{
			flex:1,
			backgroundColor:'#fff',
			alignItems:'center'
		},
		spinner:{
			flex:1,
			backgroundColor:'#fff',
			justifyContent:'center',
			alignItems:'center'
		},
		errorContainer:{
			flex:1,
			justifyContent:'center',
			alignItems:'center'
		},
		errorMessage:{
			fontSize:22
		},
		name:{
			fontSize:22,
			marginTop:10
		},
		role:{
			fontSize:18,
			marginTop:40
		},
		email:{
			fontSize:18,
			marginTop:10
		}
};